config/routes.rb
Metapost::Application.routes.draw do
  get "mpapi/add"
  get "mpapi/get"
  get "sessions/new"
  get "users/new"
  get "routes/show"
  get "routes/add"
  get "main/index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "main#index"
  resources :users
  resources :sessions
end

app/models/marker.rb
class Marker < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
     attr_accessible :from_uid, :to_uid, :text, :msgdate, :subject

end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :id
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
#encoding: utf-8

class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      puts :params;
      params.require(:message).permit(:from_uid, :to_uid, :text, :msgdate, :subject)
    end
end

app/controllers/mpapi_controller.rb
class MpapiController < ApplicationController
  layout  false
  def get

    @trk = {}
    @hash = {}

    @tracks = Track.all

    @tracks.each do |track|
      @markers = Marker.where(tid: track.id)
      @markerData = Gmaps4rails.build_markers(@markers) do |marker, mrk|
        mrk.lat marker.lat
        mrk.lng marker.lng
      end
      @trk = {track.id => {descr: track.about, start:track.start, markers: @markerData}}
      puts @trk.to_json
      @hash.merge!(@trk)
    end

  #  @hash = {}

  end

  def add

    tmptrack = Track.new

    @mrk = JSON.parse(params[:markers])

    tmptrack.uid = current_user.id
    tmptrack.start = params[:start]
    tmptrack.about = params[:descr]

    tmptrack.save

    @mrk.each do |mark|
      tmpMark = Marker.new
      tmpMark.lat = mark["mb"]
      tmpMark.lng = mark["nb"]
      tmpMark.tid = tmptrack.id
      tmpMark.save
    end

  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def new
end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mpapi_helper.rb
module MpapiHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Metapost" %></title>
		<%= csrf_meta_tags %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>

		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

		<%= javascript_include_tag "application" %>
	</head>
	<body>
		<%= render "shared/menu" %>

		<div class="container">
			<div class="row">
				<div class="span9">
					<%= bootstrap_flash %>
					<%= yield %>
				</div>
			</div><!--/row-->

			<%= render "shared/footer" %>
		</div>
		<!-- /container -->
	</body>
</html>

app/views/layouts/bak_main.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Metapost" %></title>
		<%= csrf_meta_tags %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

		<%= javascript_include_tag "application" %>
	</head>
	<body>

		<%= render "shared/menu" %>

		<div class="container">
			<div class="row">
				<div class="span9">
					<%= bootstrap_flash %>
					<%= yield %>
	
				</div>

			</div><!--/row-->

			<%= render "shared/footer" %>

		</div>
		<!-- /container -->

	</body>
</html>

app/views/layouts/routes.html.erb
<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Metapost" %></title>
		<%= csrf_meta_tags %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= stylesheet_link_tag "datepicker", :media => "all" %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag "bootstrap-datepicker" %>

	</head>
	<body>

		<%= render "shared/menu" %>

		<div class="container">
			<div class="row">
				<div class="span9">
					<%= bootstrap_flash %>
					<%= yield %>

				</div>
				<div class="span3">

				</div><!--/span-->
			</div><!--/row-->

			<%= render "shared/footer" %>

		</div>
		<!-- /container -->

	</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_uid %><br>
    <%= f.number_field :from_uid %>
  </div>
  <div class="field">
    <%= f.label :to_uid %><br>
    <%= f.number_field :to_uid %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :msgdate %><br>
    <%= f.datetime_select :msgdate %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
# coding: utf-8
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
#encoding: utf-8

<h1>Список сообщений</h1>

<table class="table table-condensed" id="tracks_table">>
  <thead>
    <tr>
      <th>От</th>
      <th>Кому</th>
      <th>Текст</th>
      <th>Дата отправки</th>
      <th>Тема</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.from_uid %></td>
        <td><%= message.to_uid %></td>
        <td><%= link_to truncate(message.text), message %></td>
        <td><%= message.msgdate %></td>
        <td><%= message.subject %></td>
        <td><%= %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Новое сообщение', new_message_path , :method => :get , :class => "btn" %>

app/views/messages/new.html.erb
# coding: utf-8
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
# coding: utf-8

<p id="notice">
	<%= notice %>
</p>

<strong>От: </strong>
<%= @message.from_uid %>

<p>
	<strong>Тема:</strong>
	<%= @message.subject %>
</p>


<strong>Текст сообщения:</strong>

<blockquote>
	<p>
		<%= @message.text %>
	</p>
</blockquote>

	<textarea rows="3" placeholder="Введите описание" id="descr_text"></textarea>		

<%= button_to 'Ответить', messages_path,  :method => :get , :class => "btn btn-primary" %>

<%= button_to 'Назад', messages_path,  :method => :get , :class => "btn" %>

app/views/mpapi/add.html.erb
<%=raw @ar.to_json %>

app/views/mpapi/get.html.erb
<%=raw @hash.to_json %>

app/views/routes/add.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script type="text/javascript" charset="utf-8"></script>

<legend>
	Новый маршрут
</legend>

<div id="map_canvas" style='width: 800px; height: 400px;'></div>
<br>

<div class="span4">
	<label>Отправка</label>
	<div class="input-append date" id="dp1" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
		<input class="span2" size="16" type="text" value="12-02-2012">
		<span class="add-on"><i class="icon-th"></i></span>
	</div>

	<label>Прибытие</label>
	<div class="input-append date" id="dp2" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
		<input class="span2" size="16" type="text" value="12-02-2012">
		<span class="add-on"><i class="icon-th"></i></span>
	</div>
	<button class="btn btn-success" id="send_btn" >
		<i class="icon-white icon-zoom-in"></i> Добавить Маршрут
	</button>

</div>
<div class="span4">
	<label>Описание</label>
	<textarea rows="3" placeholder="Введите описание" id="descr_text"></textarea>		
</div>
<br>

<%= javascript_include_tag 'gmapsstuff' %>
<script type="text/javascript">
	buildMap();
	$(document).ready(function() {
		// Handler for .ready() called.
		$('#dp1').datepicker();
		$('#dp2').datepicker();
	});

	//load map when button click (replace with what you want)
	$('#send_btn').click(function() {

		//alert("dassdf");
		$.ajax({
			type : "GET",
			url : "/mpapi/add",
			data : {
				start: $('#dp1').data('date'),
				end: $('#dp2').data('date'),
				descr: $('#descr_text').val(),
				markers : JSON.stringify(poly.getPath().getArray())
			},
			success : function() {
				alert("Маршрут добавлен!");
			}
		});
	});

</script>

app/views/routes/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script type="text/javascript" charset="utf-8"></script>

<h1>Поиск маршрута</h1>

<div style='width: 80%px;'>
	<div id="map_canvas" style='width: 80%; height: 400px;'></div>
</div>

<div class="span4">
	<label>Отправка</label>
	<div class="input-append date" id="dp1" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
		<input class="span2" size="16" type="text" value="12-02-2012">
		<span class="add-on"><i class="icon-th"></i></span>
	</div>
<br>
	<button class="btn btn-success" id="send_btn">
		<i class="icon-white icon-zoom-in"></i> Поиск
	</button>

</div>

<table class="table table-condensed" id="tracks_table">

</table>

<%= javascript_include_tag 'gmapsstuff' %>

<script type="text/javascript">
	buildMap();

	$(document).ready(function() {
		// Handler for .ready() called.
		$('#dp1').datepicker();
		$('#dp2').datepicker();
	});

	//load map when button click (replace with what you want)
	$('#send_btn').click(function() {

		$.ajax({
			type : "GET",
			url : "/mpapi/get",
			data : {
				start : $('#dp1').data('date'),
				markers : JSON.stringify(poly.getPath().getArray())
			},
			success : function(data) {
				data=JSON.parse(data);
				var tbl_body = "<tr> <th>ID</th> <th>Описание</th> <th>Дата отправки</th> </tr>";

				$.each(data, function(index) {
					var tbl_row = "";
					var track = data[index];
					console.log("data-- " + JSON.stringify(data[index]));
					tbl_row += "<td>" + index + "</td>";
					tbl_row += "<td>" + JSON.stringify(data[index].descr) + "</td>";
					tbl_row += "<td>" + JSON.stringify(data[index].start) + "</td>";
					//tbl_row += "<td>" + JSON.stringify(data[index].descr ) + "</td>";
					console.log("track:" + JSON.stringify(data[index].descr));
					$.each(track, function(ind) {
						//placeMarker(new google.maps.LatLng(track[ind].lat, track[ind].lng, true), map);
					});
					tbl_body += "<tr>" + tbl_row + "</tr>";
					//alert(data[index].lng);
				});

				$("#tracks_table").html(tbl_body);
			}
		});
	});

</script>

app/views/shared/_footer.html.erb
<footer>
	<p>

		&copy; Julian Russinhoff 2014
	</p>
</footer>

app/views/shared/_menu.html.erb
<div class="navbar navbar-static-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
			<%= image_tag "delivery_icon.png",  class: "brand"  %>
			<a class="brand" href="#">Metapost</a>

			<div class="container nav-collapse ">
				<ul class="nav nav-justified">

					<li>
						<%= link_to "Главная", "/main/index"  %>
					</li>
					<% if current_user %>
					<li>
						<span class="glyphicon glyphicon-star"></span>
						<%= link_to "Поиск", "/routes/show"  %>
					</li>

					<li>
						<%= link_to "Добавить", "/routes/add"  %>
					</li>

					<% end %>

				</ul>
				<ul class="navbar-search pull-right">

					<% if current_user %>
					Logged in as <%= current_user.email %>.
					<%= link_to "Log out", log_out_path %>
					<% else %>

					<%= link_to "Sign up", sign_up_path %> or

					<%= link_to "log in", log_in_path %>

					<% end %>

				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email, "Адрес email" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password , "Пароль" %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Подтверждение пароля"%><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit "Зарегистрироваться" , :class => "btn btn-success"%></p>
<% end %>